# Generated by Django 4.2.11 on 2024-05-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="issue_date",
        ),
    ]
