# Generated by Django 4.2.11 on 2024-05-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_remove_purchaseorder_issue_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(default="2024-05-01T10:00:00"),
            preserve_default=False,
        ),
    ]
